services:
  dynamodb-local:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - AWS_DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=us-east-1
    depends_on:
      - dynamodb-local