spring.application.name=orderServiceFan

server.port=8080
server.address=0.0.0.0

# Disable old Postgres datasource
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# DynamoDB endpoint
# Local: AWS_DYNAMODB_ENDPOINT=http://localhost:8000
# EC2: AWS_DYNAMODB_ENDPOINT empty
aws.dynamodb.endpoint=${AWS_DYNAMODB_ENDPOINT:}
aws.region=${AWS_REGION:us-east-1}

# Map /actuator/health to /health
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=health
management.endpoint.health.show-details=always





