spring.application.name=orderServiceFan

server.port=8080
server.address=0.0.0.0

# Database user connection
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orders_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true

# Map /actuator/health to /health
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=health

management.endpoint.health.show-details=always





